# Generated by Django 5.2 on 2025-04-22 19:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usercourse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrolled_users',
            field=models.ManyToManyField(blank=True, related_name='my_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserCourse',
        ),
    ]
