# Generated by Django 5.2 on 2025-05-02 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_maruza'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('1', 'Erkak'), ('2', 'Ayol')], max_length=1, null=True)),
                ('region', models.CharField(blank=True, choices=[('', 'Tanlang'), ('2', 'Andijon viloyati'), ('3', 'Buxoro viloyati'), ('12', "Farg'ona viloyati"), ('4', 'Jizzax viloyati'), ('7', 'Namangan viloyati'), ('6', 'Navoiy viloyati'), ('5', 'Qashqadaryo viloyati'), ('1', "Qoraqalpog'iston Respublikasi"), ('8', 'Samarqand viloyati'), ('10', 'Sirdaryo viloyati'), ('9', 'Surxondaryo viloyati'), ('14', 'Toshkent shahri'), ('11', 'Toshkent viloyati'), ('13', 'Xorazm viloyati')], max_length=2, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
